# Generated by Django 5.2.2 on 2025-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name="ID de l'utilisateur")),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde du compte')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du compte')),
                ('type_compte', models.CharField(choices=[('epargne', 'Épargne'), ('courant', 'Courant')], default='courant', max_length=50, verbose_name='Type de compte')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('fermé', 'Fermé')], default='actif', max_length=20, verbose_name='Statut du compte')),
            ],
        ),
    ]
